export const languageForms = {
  def: "Define one or more values in the current environment.",
  defun: "Define a named function.",
  defmacro: "Define a named macro.",
  lambda: "Create an anonymous function.",
  macro: "Create a macro.",
  cond: "Evaluate the expression belonging to the first truthy condition.",
  if: "Evaluate one of two expressions based on a condition.",
  begin: "Evaluate expressions in order and return the final result.",
  where: "Evaluate expressions in a child lexical environment.",
  loop: "Create an iterative loop with named bindings.",
  recur: "Continue the nearest loop with replacement binding values.",
  import: "Import an iamlisp extension module.",
  quote: "Return an expression without evaluating it.",
  eval: "Evaluate code represented as data.",
  apply: "Call a function with a collection of arguments.",
  print: "Send evaluated values to the configured print function.",
  typeof: "Return the iamlisp type name of a value.",
  array: "Create a JavaScript array.",
  list: "Create an iamlisp linked list. Requires the list extension.",
  map: "Transform every value in a list. Requires the list extension.",
  filter: "Keep list values matching a predicate. Requires the list extension.",
  reduce: "Fold a list into one value. Requires the list extension.",
  defmulti: "Define a multimethod.",
  defmethod: "Add a method implementation to a multimethod.",
  "set!": "Update an existing lexical binding.",
  get: "Read a property or Map entry.",
  set: "Set a property or Map entry.",
  has: "Test whether an object or Map contains a key."
};

export const operators = [
  "+",
  "-",
  "*",
  "/",
  "//",
  "%",
  ">",
  "<",
  ">=",
  "<=",
  "=",
  "!=",
  "and",
  "or",
  "not"
];

export const completionNames = [
  ...Object.keys(languageForms),
  ...operators,
  "inc",
  "dec",
  "zero?",
  "pos?",
  "neg?",
  "even?",
  "odd?",
  "abs",
  "floor",
  "ceil",
  "round",
  "true",
  "false",
  "null",
  "undefined",
  "else"
].sort();
